export const TYPES = {
  SiApiUrl: Symbol.for('SiApiUrl'),
  SiApiClient: Symbol.for('SiApiClient'),
  Translation: Symbol.for('I18n'),
  AuthToken: Symbol.for('AuthToken'),
  ServerUri: Symbol.for('ServerUri'),
  SignalRClient: Symbol.for('SignalRClient'),
  GamesService: Symbol.for('GamesService'),
  ModalsService: Symbol.for('ModalsService'),
  ToastsService: Symbol.for('ToastsService'),
  GameController: Symbol.for('GameController'),
  SoundsService: Symbol.for('SoundsService'),
  AppSettingsService: Symbol.for('AppSettingsService'),
  Storage: Symbol.for('Storage'),
  LogsService: Symbol.for('LogsService'),
  AuthService: Symbol.for('AuthService'),
  AssetsService: Symbol.for('AssetsService'),
};
