export enum MessageType {
  Info2 = 'INFO2',
  Info = 'INFO',
  ShowTablo = 'SHOWTABLO',
  Config = 'CONFIG',
  QuestionType = 'QTYPE',
  Replic = 'REPLIC',
  Atom = 'ATOM',
  Try = 'TRY',
  Choice = 'CHOICE',
  Sums = 'SUMS',
  RoundThemes = 'ROUNDTHEMES',
  RightAnswer = 'RIGHTANSWER',
  Tablo2 = 'TABLO2',
  GameThemes = 'GAMETHEMES',
  AddTable = 'ADDTABLE',
  Connected = 'CONNECTED',
  Disconnect = 'DISCONNECT',
  Disconnected = 'DISCONNECTED',
}
