export enum SendMessageType {
  Info = 'INFO',
  Answer = 'ANSWER',
  Stake = 'STAKE',
  Try = 'I',
  Choice = 'CHOICE',
  Delete = 'DELETE',
  Ready = 'READY',
  Atom = 'ATOM',
  Cat = 'CAT',
  CatCost = 'CATCOST',
  FinalStake = 'FINALSTAKE',
  IsRight = 'ISRIGHT',
  Picture = 'PICTURE',
}
