export enum AppSound {
  AnswerWrong = 'answer_wrong',
  ApplauseBig = 'applause_big',
  ApplauseFinal = 'applause_final',
  ApplauseSmall = 'applause_small',
  FinalDelete = 'final_delete',
  FinalThink = 'final_think',
  MainMenu = 'main_menu',
  QuestionNoAnswers = 'question_noanswers',
  QuestionNoRisk = 'question_norisk',
  QuestionSecret = 'question_secret',
  QuestionStake = 'question_stake',
  RoundBegin = 'round_begin',
  RoundThemes = 'round_themes',
  RoundTimeout = 'round_timeout',
}
